/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface DriverSchema {
  /**
   * Unknown Property
   */
  [x: string]: any;
  dob: Date;
  licenseNo: string;
  name: string;
  password: string;
  sex?: 'M' | 'F' | 'O';
}

export type FleetSchema = ({
  driver?: {
    /**
     * Unknown Property
     */
    [x: string]: any;
    dob: Date;
    licenseNo: string;
    name: string;
    password: string;
    sex?: 'M' | 'F' | 'O';
  };
  vehicle?: {
    length: number;
    seats: number;
    type: 'car' | 'bus';
  };
})[];

export interface PersonFormSchema {
  /**
   * Unknown Property
   */
  [x: string]: any;
  dob: Date;
  name: string;
  password: string;
  repeatPassword: string;
  sex?: 'M' | 'F' | 'O';
}

export interface PersonSchema {
  /**
   * Unknown Property
   */
  [x: string]: any;
  dob: Date;
  name: string;
  password: string;
  sex?: 'M' | 'F' | 'O';
}

export interface VehicleSchema {
  length: number;
  seats: number;
  type: 'car' | 'bus';
}
