/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface VehicleSchema {
  length: number;
  seats: number;
  type: 'car' | 'bus';
}
